# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: birb/birb_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62irb/birb_server.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n\tBirbEvent\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08playerId\x18\x02 \x01(\x03\x12\x0f\n\x07session\x18\x03 \x01(\t\x12\x11\n\teventType\x18\x04 \x01(\x03\x12\x11\n\teventJson\x18\x05 \x01(\t\x12-\n\tcreatedAt\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"b\n\nBirbPlayer\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02\x61i\x18\x03 \x01(\x08\x12\x0f\n\x07session\x18\x04 \x01(\t\x12\x0e\n\x06userId\x18\x05 \x01(\x03\x12\r\n\x05state\x18\x06 \x01(\x03\"S\n\tGameState\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12\"\n\x0cplayerStates\x18\x02 \x03(\x0b\x32\x0c.PlayerState\x12\x14\n\x0cWaitingOnIds\x18\x03 \x03(\x03\"N\n\x10GameStateRequest\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12\x1c\n\x07players\x18\x02 \x03(\x0b\x32\x0b.BirbPlayer\x12\x0e\n\x06\x65vents\x18\x03 \x03(\x05\"H\n\x0cPlayerAction\x12\x10\n\x08playerId\x18\x01 \x01(\x03\x12\x12\n\nactionType\x18\x02 \x01(\x03\x12\x12\n\nactionJson\x18\x03 \x01(\t\"[\n\x0bPlayerState\x12\x10\n\x08playerId\x18\x01 \x01(\x03\x12\x11\n\tstateJson\x18\x02 \x01(\t\x12\'\n\x10\x61vailableActions\x18\x03 \x03(\x0b\x32\r.PlayerAction\"~\n\x15ValidateActionRequest\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12\x1d\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\r.PlayerAction\x12\x1c\n\x07players\x18\x03 \x03(\x0b\x32\x0b.BirbPlayer\x12\x1a\n\x06\x65vents\x18\x04 \x03(\x0b\x32\n.BirbEvent\"2\n\x12ValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2t\n\x04\x42irb\x12-\n\x0cGetGameState\x12\x11.GameStateRequest\x1a\n.GameState\x12=\n\x0eValidateAction\x12\x16.ValidateActionRequest\x1a\x13.ValidationResponseB2Z\x1fgithub.com/birbparty/proto/birb\xaa\x02\x0e\x42irbParty.Grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'birb.birb_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/birbparty/proto/birb\252\002\016BirbParty.Grpc'
  _BIRBEVENT._serialized_start=60
  _BIRBEVENT._serialized_end=203
  _BIRBPLAYER._serialized_start=205
  _BIRBPLAYER._serialized_end=303
  _GAMESTATE._serialized_start=305
  _GAMESTATE._serialized_end=388
  _GAMESTATEREQUEST._serialized_start=390
  _GAMESTATEREQUEST._serialized_end=468
  _PLAYERACTION._serialized_start=470
  _PLAYERACTION._serialized_end=542
  _PLAYERSTATE._serialized_start=544
  _PLAYERSTATE._serialized_end=635
  _VALIDATEACTIONREQUEST._serialized_start=637
  _VALIDATEACTIONREQUEST._serialized_end=763
  _VALIDATIONRESPONSE._serialized_start=765
  _VALIDATIONRESPONSE._serialized_end=815
  _BIRB._serialized_start=817
  _BIRB._serialized_end=933
# @@protoc_insertion_point(module_scope)
